2019-09-01 22:14:29,333 ERROR: Exception on /index [GET] [in /Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/routes.py", line 22, in index
    posts=posts)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_posts.html' %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _posts.html
2019-09-01 22:14:31,087 ERROR: Exception on /index [GET] [in /Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/routes.py", line 22, in index
    posts=posts)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_posts.html' %}
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _posts.html
2019-09-01 22:15:14,818 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:34]
2019-09-01 22:27:21,996 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:34]
2019-09-01 22:47:52,258 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:34]
2019-09-01 22:50:35,202 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:34]
2019-09-01 23:00:23,398 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:34]
