2019-09-03 11:30:33,616 ERROR: Exception on /index [GET] [in /Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/routes.py", line 29, in index
    prev_url=prev_url)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/app/templates/index.html", line 22, in template
    <a href="{{ next_url or '#' }}">
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/amyliz/Documents/Computer Science/Python/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-09-03 11:34:01,957 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:38]
2019-09-04 08:56:05,100 INFO: Microblog startup [in /Users/amyliz/Documents/Computer Science/Python/microblog/app/__init__.py:40]
